version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: remark-math
    versions:
    - ">= 4.a, < 5"
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 3.3.0
    - 3.3.1
  - dependency-name: gatsby-remark-images
    versions:
    - 5.0.0
  - dependency-name: katex
    versions:
    - 0.13.0
    - 0.13.1
    - 0.13.2
  - dependency-name: gatsby-image
    versions:
    - 3.0.0
  - dependency-name: gatsby-plugin-mdx
    versions:
    - 2.0.0
  - dependency-name: gatsby-plugin-typescript
    versions:
    - 2.12.1
  - dependency-name: gatsby-transformer-remark
    versions:
    - 2.16.1
    - 4.0.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.11.1
  - dependency-name: gatsby-plugin-image
    versions:
    - 0.6.3
    - 0.6.4
    - 0.7.1
    - 0.7.2
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 3.3.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 3.3.0
  - dependency-name: gatsby-remark-prismjs
    versions:
    - 5.0.0
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
