name: deployment

on: [push]

env:
  GCLOUD_REGION: us-central1
  GCLOUD_PLATFORM: managed

jobs:
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - continue-on-error: false
        name: Setup Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: gcloud test
        run: gcloud --version
