name: Website CD

on:
  push:
    branches: 
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to production 
    
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: deploy to production
      env:
        GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
      run: |
        BUILD_DIR="$PWD/build/"
        SHORT_COMMIT_HASH=$(git log --format="%h" -n 1)
        cd ~
        git clone https://github.com/AbhyudayaSharma/abhyudayasharma.github.io/ build
        cd build
        git checkout master
        rm -rf $(git ls-files)
        cp -R $BUILD_DIR/* .
        git add -A
        git -c user.email='deploy-bot' -c user.name='deploy-bot' commit -m "Deploy $SHORT_COMMIT_HASH at $(date)" --allow-empty
        git push -f -q "https://AbhyudayaSharma:$GITHUB_TOKEN@github.com/AbhyudayaSharma/abhyudayasharma.github.io"
        cd "$BUILD_DIR/../"
