name: build

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install -g npm@8.3.1
      - name: npm install, build and test
        run: |
          npm ci
          npm run build --if-present
          npm run lint
          npm run lint-md
          npm test -- --verbose
      - name: Code coverage
        if: false && contains(matrix.os, 'ubuntu') && contains(matrix.node-version, '16') # TODO: enable when tests is ready
        run: |
          npm test -- --coverage --verbose
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report --coverage-reports coverage/lcov.info
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      - name: Archive build
        if: contains(matrix.os, 'ubuntu') && contains(matrix.node-version, '16')
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: public/
    env:
      CI: true

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    concurrency: production-environment
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/
      - name: Deploy to Nginx
        shell: pwsh
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          ./deploy.ps1
