name: Website CD

on:
  push:
    branches-ignore:
    - master

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        # TODO enable Windows builds
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm run lint
        npm test -- --coverage --verbose
    env:
      CI: true

# TODO deployment script
